// <auto-generated />
namespace INT1448.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Add_annotation_no_mapped : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_annotation_no_mapped));
        
        string IMigrationMetadata.Id
        {
            get { return "202004130906202_Add_annotation_no_mapped"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
