// <auto-generated />
namespace INT1448.EntityFramework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class update_navigation_property : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_navigation_property));
        
        string IMigrationMetadata.Id
        {
            get { return "202004161557289_update_navigation_property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
